# Formatting
max_width = 99
format_strings = true
#imports_indent = "block" (see https://github.com/rust-lang-nursery/rustfmt/issues/2596)
match_block_trailing_comma = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
blank_lines_upper_bound = 2

# Import reordering
reorder_imported_names = true
reorder_imports = true

# Reporting
report_todo = "unnumbered"
report_fixme = "unnumbered"
