[package]
name = "push-relay"
version = "1.0.0"
authors = ["Danilo Bargen <danilo.bargen@threema.ch>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/threema-ch/push-relay"

[dependencies]
iron = "0.6"
iron-cors = "0.7"
router = "0.6"
urlencoded = "0.6"
hyper = "0.10"
hyper-native-tls = "0.2"
quick-error = "1.1"
rustc-serialize = "0.3"
chrono = "0.4"
clap = "2"
rust-ini = "0.10"
log = "0.4"
env_logger = "0.5"

[dev-dependencies]
iron-test = "0.6"
mockito = "0.9"
