[package]
name = "push-relay"
version = "0.4.0"
authors = ["Danilo Bargen <danilo.bargen@threema.ch>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/threema-ch/push-relay"

[dependencies]
iron = "0.4"
iron-cors = "0.4"
router = "0.4"
urlencoded = "0.4"
hyper = "0.9"
quick-error = "1.1"
rustc-serialize = "0.3"
chrono = "0.2"
clap = "2"
rust-ini = "0.10"
log = "0.3"
env_logger = "0.4"

[dev-dependencies]
iron-test = "0.4.0"
mockito = "0.2"
