version: 2

jobs:

  test:
    docker:
      - image: rust:1.30
    steps:
      - checkout
      # Load cargo target from cache if possible.
      # Multiple caches are used to increase the chance of a cache hit.
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ checksum "Cargo.lock" }}
            - v4-cargo-cache-{{ .Branch }}
            - v4-cargo-cache
      - run: cargo build && cargo test
      - save_cache:
          key: v4-cargo-cache-{{ checksum "Cargo.lock" }}
          paths:
            - target
            - /usr/local/cargo
      - save_cache:
          key: v4-cargo-cache-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
      - save_cache:
          key: v4-cargo-cache
          paths:
            - target
            - /usr/local/cargo
  audit:
    docker:
      - image: rust:1.28
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cargo-audit-cache
      - run:
          name: Install dependencies
          command: apt update && apt install -y cmake
      - run:
          name: Install and run cargo-audit
          command: cargo install --force cargo-audit && cargo audit
      - save_cache:
          key: v1-cargo-audit-cache
          paths:
            - /usr/local/cargo

workflows:
  version: 2

  # Build on push
  on_push:
    jobs:
      - test
      - audit

  # Build master every week on Monday at 04:00 am
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
      - audit
